### ISSUE TITLE
UI Input?

### ISSUE THREAD

**Issue by Goki227** [bitobrian/Gratwurst#26]
When I open the config box from within game I can't paste or type into the message box. What am I missing? TIA

**Comment by bitobrian** [comment]
The default input box has always been finicky. There's usually a spot that is where the first line would be that you need to click into first.

It's also possible that something might've broke. I was working on fixing it up late last year for dragonflight, but admittedly fell off my radar. @jimeherr Are you still using the addon currently?

**Comment by jimeherr** [comment]
I am, and it is indeed the entry field being finicky.  You have to click on the what would be considered the top line to get a cursor to start.  We can look into seeing if there's a way to auto focus that, but I'm not certain.  

Once you get the cursor going, pasting or typing should work as normal.

**Comment by Goki227** [comment]
Thanks, you two. I was able to get it going.
