### ISSUE TITLE
See if we can parse Player names

### ISSUE THREAD

**Issue by bitobrian** [bitobrian/Gratwurst#4]
It would be neat to send a message like you were responding back to that individual.

**Comment by jimeherr** [comment]
I think we should parse, and if the user puts in a specific string like <playername> in their message, we replace.

**Comment by jimeherr** [comment]
It is easy to pull the name of the person(s) receiving the achievement, I did that for preventing self congrats.  However, what about the scenario where multiple people achieve the same achiev at the same time, say in a dungeon run?  I don't know if there is a way to catch those events, store them, determine if there are multiple events at the same time, and then use a group pronoun?
